// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type Agent = {
    apiVersion: string;
    kind: string;
    metadata: ObjectMeta;
    spec: AgentSpec;
    status?: Status;
};

export type AgentSource = {
    image?: string;
    protocol?: 'A2A' | 'HTTP' | 'OpenAIResponses';
    repository?: Repository;
};

export type AgentSpec = {
    /**
     * @deprecated
     */
    compatibleHarnesses?: Array<HarnessCompatibility> | null;
    description?: string;
    iconUrl?: string;
    instructions?: ResourceRef;
    mcpServers?: Array<ResourceRef> | null;
    /**
     * @deprecated
     */
    modelName?: string;
    /**
     * @deprecated
     */
    modelProvider?: string;
    plugins?: Array<ResourceRef> | null;
    skills?: Array<ResourceRef> | null;
    source?: AgentSource;
    title?: string;
};

export type ApplyResult = {
    apiVersion?: string;
    error?: string;
    kind?: string;
    name: string;
    namespace?: string;
    status: string;
    tag?: string;
};

export type ApplyResultsResponse = {
    results: Array<ApplyResult> | null;
};

export type CommandEntry = {
    allowedTools?: Array<string> | null;
    argumentHint?: string;
    content?: string;
    description?: string;
    model?: string;
    source?: string;
};

export type CommandsField = {
    Map: {
        [key: string]: CommandEntry;
    };
    Paths: PathOrPaths;
};

export type Condition = {
    lastTransitionTime?: string;
    message?: string;
    reason?: string;
    status: string;
    type: string;
};

export type Deployment = {
    apiVersion: string;
    kind: string;
    metadata: ObjectMeta;
    spec: DeploymentSpec;
    status?: Status;
};

export type DeploymentHarness = {
    permissionMode?: string;
    type: string;
};

export type DeploymentRef = {
    name: string;
    namespace?: string;
};

export type DeploymentSpec = {
    deploymentRefs?: Array<DeploymentRef> | null;
    desiredState?: string;
    env?: {
        [key: string]: string;
    };
    harness?: DeploymentHarness;
    modelRef?: ModelRef;
    runtimeConfig?: {
        [key: string]: unknown;
    };
    runtimeRef: ResourceRef;
    targetRef: ResourceRef;
};

export type ErrorDetail = {
    /**
     * Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'
     */
    location?: string;
    /**
     * Error message text
     */
    message?: string;
    /**
     * The value at the given location
     */
    value?: unknown;
};

export type ErrorModel = {
    /**
     * A human-readable explanation specific to this occurrence of the problem.
     */
    detail?: string;
    /**
     * Optional list of individual error details
     */
    errors?: Array<ErrorDetail> | null;
    /**
     * A URI reference that identifies the specific occurrence of the problem.
     */
    instance?: string;
    /**
     * HTTP status code
     */
    status?: number;
    /**
     * A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
     */
    title?: string;
    /**
     * A URI reference to human-readable documentation for the error.
     */
    type?: string;
};

export type HttpHeader = {
    name: string;
    value?: string;
};

export type HarnessCompatibility = {
    type: string;
};

export type HealthBody = {
    /**
     * Health status
     */
    status: string;
};

export type HookEntry = {
    allowedEnvVars?: Array<string> | null;
    async?: boolean;
    asyncRewake?: boolean;
    command?: string;
    headers?: {
        [key: string]: string;
    };
    if?: string;
    input?: unknown;
    model?: string;
    once?: boolean;
    prompt?: string;
    server?: string;
    shell?: string;
    statusMessage?: string;
    timeout?: number;
    tool?: string;
    type: string;
    url?: string;
};

export type HookMatcherGroup = {
    hooks: Array<HookEntry> | null;
    matcher?: string;
};

export type HooksField = {
    Events: {
        [key: string]: Array<HookMatcherGroup> | null;
    };
    Path: string;
    Raw: unknown;
};

export type LspServerEntry = {
    args?: Array<string> | null;
    command: string;
    env?: {
        [key: string]: string;
    };
    extensionToLanguage: {
        [key: string]: string;
    };
    initializationOptions?: unknown;
    maxRestarts?: number;
    settings?: unknown;
    startupTimeout?: number;
    transport?: string;
    workspaceFolder?: string;
};

export type LspServersField = {
    Path: string;
    Raw: unknown;
    Servers: {
        [key: string]: LspServerEntry;
    };
};

export type ListMetadata = {
    count: number;
    nextCursor?: string;
};

export type ListOutputAgentBody = {
    items: Array<Agent> | null;
    nextCursor?: string;
};

export type ListOutputDeploymentBody = {
    items: Array<Deployment> | null;
    nextCursor?: string;
};

export type ListOutputMcpServerBody = {
    items: Array<McpServer> | null;
    nextCursor?: string;
};

export type ListOutputModelBody = {
    items: Array<Model> | null;
    nextCursor?: string;
};

export type ListOutputPluginBody = {
    items: Array<Plugin> | null;
    nextCursor?: string;
};

export type ListOutputPromptBody = {
    items: Array<Prompt> | null;
    nextCursor?: string;
};

export type ListOutputRuntimeBody = {
    items: Array<Runtime> | null;
    nextCursor?: string;
};

export type ListOutputSecretBody = {
    items: Array<Secret> | null;
    nextCursor?: string;
};

export type ListOutputSkillBody = {
    items: Array<Skill> | null;
    nextCursor?: string;
};

export type LocalSecretReference = {
    name: string;
};

export type McpArgument = {
    name?: string;
    type: string;
    value?: string;
};

export type McpKeyValueInput = {
    isRequired?: boolean;
    name: string;
    value?: string;
};

export type McpPackage = {
    launch?: McpPackageLaunch;
    origin: McpPackageOrigin;
    transport: McpTransport;
};

export type McpPackageLaunch = {
    args?: Array<McpArgument> | null;
    command?: string;
    env?: Array<McpKeyValueInput> | null;
};

export type McpPackageOrigin = {
    identifier: string;
    npm?: McpPackageOriginNpm;
    oci?: McpPackageOriginOci;
    pypi?: McpPackageOriginPyPi;
    type: string;
};

export type McpPackageOriginNpm = {
    mirror?: string;
    serverName: string;
    version: string;
};

export type McpPackageOriginOci = {
    serverName: string;
};

export type McpPackageOriginPyPi = {
    mirror?: string;
    serverName: string;
    version: string;
};

export type McpRemote = {
    headers?: Array<HttpHeader> | null;
    type: string;
    url: string;
};

export type McpServer = {
    apiVersion: string;
    kind: string;
    metadata: ObjectMeta;
    spec: McpServerSpec;
    status?: Status;
};

export type McpServerEntry = {
    args?: Array<string> | null;
    command?: string;
    env?: {
        [key: string]: string;
    };
    headers?: {
        [key: string]: string;
    };
    headersHelper?: string;
    oauth?: McpServerOAuth;
    type?: string;
    url?: string;
};

export type McpServerOAuth = {
    authServerMetadataUrl?: string;
    callbackPort?: number;
    clientId?: string;
    scopes?: Array<string> | null;
};

export type McpServerSource = {
    package?: McpPackage;
    repository?: Repository;
};

export type McpServerSpec = {
    description?: string;
    iconUrl?: string;
    remote?: McpRemote;
    source?: McpServerSource;
    title?: string;
};

export type McpServersField = {
    Path: string;
    Raw: unknown;
    Servers: {
        [key: string]: McpServerEntry;
    };
};

export type McpTransport = {
    path?: string;
    port?: number;
    type: string;
};

export type MarketplaceResponse = {
    $schema?: string;
    name: string;
    owner: Owner;
    plugins: Array<PluginEntry>;
};

export type Model = {
    apiVersion: string;
    kind: string;
    metadata: ObjectMeta;
    spec: ModelSpec;
    status?: Status;
};

export type ModelAuthConfig = {
    secretRef?: SecretKeyRef;
    strategy: 'runtime' | 'secretRef' | 'passthrough';
};

export type ModelEndpointConfig = {
    baseUrl?: string;
    region?: string;
    tls?: ModelTlsConfig;
};

export type ModelRef = {
    name: string;
    namespace?: string;
    tag?: string;
};

export type ModelSpec = {
    auth?: ModelAuthConfig;
    description?: string;
    endpoint?: ModelEndpointConfig;
    iconUrl?: string;
    model: string;
    provider: 'bedrock';
    title?: string;
};

export type ModelTlsConfig = {
    caCertSecretRef?: SecretKeyRef;
    disableVerify?: boolean;
};

export type MonitorEntry = {
    command: string;
    description: string;
    name: string;
    when?: string;
};

export type MonitorsField = {
    Entries: Array<MonitorEntry> | null;
    Path: string;
};

export type ObjectMeta = {
    annotations?: {
        [key: string]: string;
    };
    createdAt?: string;
    deletionTimestamp?: string;
    labels?: {
        [key: string]: string;
    };
    name: string;
    namespace?: string;
    tag?: string;
    uid?: string;
    updatedAt?: string;
};

export type OfficialMeta = {
    isLatest: boolean;
    publishedAt?: string;
    status?: string;
    statusChangedAt?: string;
    updatedAt?: string;
};

export type Owner = {
    email?: string;
    name: string;
};

export type PathOrPaths = {
    Values: Array<string> | null;
    WasArray: boolean;
};

export type PingBody = {
    /**
     * Ping response
     */
    pong: boolean;
};

export type Plugin = {
    apiVersion: string;
    kind: string;
    metadata: ObjectMeta;
    spec: PluginSpec;
    status?: PluginStatus;
};

export type PluginAuthor = {
    email?: string;
    name: string;
    url?: string;
};

export type PluginChannel = {
    displayName?: string;
    server: string;
    userConfig?: {
        [key: string]: PluginUserConfigField;
    };
};

export type PluginDependency = {
    marketplace?: string;
    name?: string;
    version?: string;
};

export type PluginEntry = {
    description?: string;
    name: string;
    source: unknown;
    version?: string;
};

export type PluginExperimental = {
    monitors?: MonitorsField;
    themes?: PathOrPaths;
};

export type PluginHook = {
    event: string;
    type?: string;
};

export type PluginInventory = {
    agents?: Array<string> | null;
    commands?: Array<string> | null;
    executables?: Array<string> | null;
    hooks?: Array<PluginHook> | null;
    mcpServers?: Array<string> | null;
    skills?: Array<PluginSkill> | null;
};

export type PluginManifest = {
    $schema?: string;
    agents?: PathOrPaths;
    author?: PluginAuthor;
    channels?: Array<PluginChannel> | null;
    commands?: CommandsField;
    defaultEnabled?: boolean;
    dependencies?: Array<PluginDependency> | null;
    description?: string;
    displayName?: string;
    experimental?: PluginExperimental;
    homepage?: string;
    hooks?: HooksField;
    keywords?: Array<string> | null;
    license?: string;
    lspServers?: LspServersField;
    mcpServers?: McpServersField;
    monitors?: MonitorsField;
    name: string;
    outputStyles?: PathOrPaths;
    repository?: string;
    settings?: unknown;
    skills?: PathOrPaths;
    themes?: PathOrPaths;
    userConfig?: {
        [key: string]: PluginUserConfigField;
    };
    version?: string;
};

export type PluginResolvedSource = {
    commit?: string;
    digest?: string;
    type: string;
};

export type PluginSkill = {
    description?: string;
    name: string;
};

export type PluginSource = {
    git?: PluginSourceGit;
    oci?: PluginSourceOci;
    type: string;
};

export type PluginSourceGit = {
    repository: Repository;
};

export type PluginSourceOci = {
    reference: string;
};

export type PluginSpec = {
    description?: string;
    /**
     * @deprecated
     */
    harnesses?: Array<string> | null;
    iconUrl?: string;
    source?: PluginSource;
    title?: string;
};

export type PluginStatus = {
    conditions?: Array<Condition> | null;
    details?: unknown;
    formats?: Array<string> | null;
    inventory?: PluginInventory;
    /**
     * @deprecated
     */
    manifest?: PluginManifest;
    manifests?: {
        [key: string]: PluginManifest;
    };
    mcpServerFiles?: Array<string> | null;
    resolvedSource?: PluginResolvedSource;
};

export type PluginUserConfigField = {
    default?: unknown;
    description: string;
    max?: number;
    min?: number;
    multiple?: boolean;
    required?: boolean;
    sensitive?: boolean;
    title: string;
    type: string;
};

export type Prompt = {
    apiVersion: string;
    kind: string;
    metadata: ObjectMeta;
    spec: PromptSpec;
    status?: Status;
};

export type PromptSpec = {
    content?: string;
    description?: string;
    iconUrl?: string;
};

export type Repository = {
    branch?: string;
    commit?: string;
    credentialsRef?: LocalSecretReference;
    subfolder?: string;
    url?: string;
};

export type ResourceRef = {
    kind: string;
    name: string;
    namespace?: string;
    tag?: string;
};

export type ResponseMeta = {
    'io.modelcontextprotocol.registry/official'?: OfficialMeta;
};

export type Runtime = {
    apiVersion: string;
    kind: string;
    metadata: ObjectMeta;
    spec: RuntimeSpec;
    status?: Status;
};

export type RuntimeSpec = {
    config?: {
        [key: string]: unknown;
    };
    telemetryEndpoint?: string;
    type: string;
};

export type Secret = {
    apiVersion: string;
    kind: string;
    metadata: ObjectMeta;
    spec: SecretSpec;
    status?: SecretStatus;
};

export type SecretKeyRef = {
    key?: string;
    name: string;
    namespace?: string;
};

export type SecretSpec = {
    data?: {
        [key: string]: string;
    };
    immutable?: boolean;
    stringData?: {
        [key: string]: string;
    };
    type?: string;
};

export type SecretStatus = {
    dataKeys?: Array<string> | null;
};

export type ServerArgument = {
    name?: string;
    type: string;
    value?: string;
};

export type ServerDetail = {
    $schema?: string;
    description: string;
    name: string;
    packages?: Array<ServerPackage> | null;
    remotes?: Array<ServerTransport> | null;
    repository?: ServerRepository;
    title?: string;
    version: string;
    websiteUrl?: string;
};

export type ServerInput = {
    isRequired?: boolean;
    name: string;
    value?: string;
};

export type ServerListResponse = {
    metadata: ListMetadata;
    servers: Array<ServerResponse> | null;
};

export type ServerPackage = {
    environmentVariables?: Array<ServerInput> | null;
    fileSha256?: string;
    identifier: string;
    packageArguments?: Array<ServerArgument> | null;
    registryBaseUrl?: string;
    registryType: string;
    runtimeArguments?: Array<ServerArgument> | null;
    runtimeHint?: string;
    transport: ServerTransport;
    version: string;
};

export type ServerRepository = {
    id?: string;
    source?: string;
    subfolder?: string;
    url: string;
};

export type ServerResponse = {
    _meta?: ResponseMeta;
    server: ServerDetail;
};

export type ServerTransport = {
    headers?: Array<ServerInput> | null;
    type: string;
    url?: string;
};

export type Skill = {
    apiVersion: string;
    kind: string;
    metadata: ObjectMeta;
    spec: SkillSpec;
    status?: SkillStatus;
};

export type SkillResolvedSource = {
    commit?: string;
};

export type SkillSource = {
    repository?: Repository;
};

export type SkillSpec = {
    description?: string;
    iconUrl?: string;
    source?: SkillSource;
    title?: string;
};

export type SkillStatus = {
    conditions?: Array<Condition> | null;
    details?: unknown;
    resolvedSource?: SkillResolvedSource;
};

export type Status = {
    conditions?: Array<Condition> | null;
    details?: unknown;
};

export type VersionBody = {
    /**
     * Build timestamp
     */
    build_time: string;
    /**
     * Git commit SHA
     */
    git_commit: string;
    /**
     * Application version
     */
    version: string;
};

export type PluginMarketplaceGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/plugin-marketplace/marketplace.json';
};

export type PluginMarketplaceGetErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type PluginMarketplaceGetError = PluginMarketplaceGetErrors[keyof PluginMarketplaceGetErrors];

export type PluginMarketplaceGetResponses = {
    /**
     * OK
     */
    200: MarketplaceResponse;
};

export type PluginMarketplaceGetResponse = PluginMarketplaceGetResponses[keyof PluginMarketplaceGetResponses];

export type McpRegistryListServersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Opaque pagination cursor from a prior response.
         */
        cursor?: string;
        /**
         * Max servers to return (capped at 100).
         */
        limit?: number;
        /**
         * Substring match on the server name.
         */
        search?: string;
        /**
         * RFC3339 timestamp; only servers updated at or after this time.
         */
        updated_since?: string;
        /**
         * 'latest' (default) or a specific version tag.
         */
        version?: string;
        /**
         * Include servers pending deletion.
         */
        include_deleted?: boolean;
    };
    url: '/v0.1/servers';
};

export type McpRegistryListServersErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type McpRegistryListServersError = McpRegistryListServersErrors[keyof McpRegistryListServersErrors];

export type McpRegistryListServersResponses = {
    /**
     * OK
     */
    200: ServerListResponse;
};

export type McpRegistryListServersResponse = McpRegistryListServersResponses[keyof McpRegistryListServersResponses];

export type McpRegistryListServerVersionsData = {
    body?: never;
    path: {
        /**
         * URL-encoded '<namespace>/<name>' server name.
         */
        serverName: string;
    };
    query?: {
        cursor?: string;
        limit?: number;
        include_deleted?: boolean;
    };
    url: '/v0.1/servers/{serverName}/versions';
};

export type McpRegistryListServerVersionsErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type McpRegistryListServerVersionsError = McpRegistryListServerVersionsErrors[keyof McpRegistryListServerVersionsErrors];

export type McpRegistryListServerVersionsResponses = {
    /**
     * OK
     */
    200: ServerListResponse;
};

export type McpRegistryListServerVersionsResponse = McpRegistryListServerVersionsResponses[keyof McpRegistryListServerVersionsResponses];

export type McpRegistryGetServerVersionData = {
    body?: never;
    path: {
        /**
         * URL-encoded '<namespace>/<name>' server name.
         */
        serverName: string;
        /**
         * A specific version tag, or 'latest'.
         */
        version: string;
    };
    query?: never;
    url: '/v0.1/servers/{serverName}/versions/{version}';
};

export type McpRegistryGetServerVersionErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type McpRegistryGetServerVersionError = McpRegistryGetServerVersionErrors[keyof McpRegistryGetServerVersionErrors];

export type McpRegistryGetServerVersionResponses = {
    /**
     * OK
     */
    200: ServerResponse;
};

export type McpRegistryGetServerVersionResponse = McpRegistryGetServerVersionResponses[keyof McpRegistryGetServerVersionResponses];

export type ListAgentsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Namespace (defaults to 'default'; 'all' lists across all namespaces).
         */
        namespace?: string;
        /**
         * Max items to return (default 50).
         */
        limit?: number;
        /**
         * Opaque pagination cursor.
         */
        cursor?: string;
        /**
         * Label selector: key=value,key2=value2.
         */
        labels?: string;
        /**
         * Restrict the result set to one tag value (tagged artifact kinds only).
         */
        tag?: string;
        /**
         * Only return the literal latest tag per (namespace, name). Equivalent to tag=latest for tagged kinds.
         */
        latestOnly?: boolean;
        /**
         * Include rows with a deletionTimestamp.
         */
        includeTerminating?: boolean;
    };
    url: '/v0/agents';
};

export type ListAgentsErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ListAgentsError = ListAgentsErrors[keyof ListAgentsErrors];

export type ListAgentsResponses = {
    /**
     * OK
     */
    200: ListOutputAgentBody;
};

export type ListAgentsResponse = ListAgentsResponses[keyof ListAgentsResponses];

export type GetLatestAgentData = {
    body?: never;
    path: {
        name: string;
    };
    query?: {
        /**
         * Namespace (internal; defaults to 'default').
         */
        namespace?: string;
    };
    url: '/v0/agents/{name}';
};

export type GetLatestAgentErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetLatestAgentError = GetLatestAgentErrors[keyof GetLatestAgentErrors];

export type GetLatestAgentResponses = {
    /**
     * OK
     */
    200: Agent;
};

export type GetLatestAgentResponse = GetLatestAgentResponses[keyof GetLatestAgentResponses];

export type DeleteAgentData = {
    body?: never;
    path: {
        name: string;
        tag: string;
    };
    query?: {
        /**
         * Namespace (internal; defaults to 'default').
         */
        namespace?: string;
    };
    url: '/v0/agents/{name}/{tag}';
};

export type DeleteAgentErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type DeleteAgentError = DeleteAgentErrors[keyof DeleteAgentErrors];

export type DeleteAgentResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteAgentResponse = DeleteAgentResponses[keyof DeleteAgentResponses];

export type GetAgentData = {
    body?: never;
    path: {
        name: string;
        tag: string;
    };
    query?: {
        /**
         * Namespace (internal; defaults to 'default').
         */
        namespace?: string;
    };
    url: '/v0/agents/{name}/{tag}';
};

export type GetAgentErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetAgentError = GetAgentErrors[keyof GetAgentErrors];

export type GetAgentResponses = {
    /**
     * OK
     */
    200: Agent;
};

export type GetAgentResponse = GetAgentResponses[keyof GetAgentResponses];

export type ListTagsAgentData = {
    body?: never;
    path: {
        name: string;
    };
    query?: {
        /**
         * Namespace (internal; defaults to 'default').
         */
        namespace?: string;
    };
    url: '/v0/agents/{name}/tags';
};

export type ListTagsAgentErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ListTagsAgentError = ListTagsAgentErrors[keyof ListTagsAgentErrors];

export type ListTagsAgentResponses = {
    /**
     * OK
     */
    200: ListOutputAgentBody;
};

export type ListTagsAgentResponse = ListTagsAgentResponses[keyof ListTagsAgentResponses];

export type DeleteBatchData = {
    body: Blob | File;
    path?: never;
    query?: {
        /**
         * Run validation without mutating the store. Defaults to false.
         */
        dryRun?: boolean;
    };
    url: '/v0/apply';
};

export type DeleteBatchErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type DeleteBatchError = DeleteBatchErrors[keyof DeleteBatchErrors];

export type DeleteBatchResponses = {
    /**
     * OK
     */
    200: ApplyResultsResponse;
};

export type DeleteBatchResponse = DeleteBatchResponses[keyof DeleteBatchResponses];

export type ApplyBatchData = {
    body: Blob | File;
    path?: never;
    query?: {
        /**
         * Run validation without mutating the store. Defaults to false.
         */
        dryRun?: boolean;
    };
    url: '/v0/apply';
};

export type ApplyBatchErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ApplyBatchError = ApplyBatchErrors[keyof ApplyBatchErrors];

export type ApplyBatchResponses = {
    /**
     * OK
     */
    200: ApplyResultsResponse;
};

export type ApplyBatchResponse = ApplyBatchResponses[keyof ApplyBatchResponses];

export type ListDeploymentsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Namespace (defaults to 'default'; 'all' lists across all namespaces).
         */
        namespace?: string;
        /**
         * Max items to return (default 50).
         */
        limit?: number;
        /**
         * Opaque pagination cursor.
         */
        cursor?: string;
        /**
         * Label selector: key=value,key2=value2.
         */
        labels?: string;
        /**
         * Restrict the result set to one tag value (tagged artifact kinds only).
         */
        tag?: string;
        /**
         * Only return the literal latest tag per (namespace, name). Equivalent to tag=latest for tagged kinds.
         */
        latestOnly?: boolean;
        /**
         * Include rows with a deletionTimestamp.
         */
        includeTerminating?: boolean;
        /**
         * Deployment origin filter: managed or discovered.
         */
        origin?: string;
    };
    url: '/v0/deployments';
};

export type ListDeploymentsErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ListDeploymentsError = ListDeploymentsErrors[keyof ListDeploymentsErrors];

export type ListDeploymentsResponses = {
    /**
     * OK
     */
    200: ListOutputDeploymentBody;
};

export type ListDeploymentsResponse = ListDeploymentsResponses[keyof ListDeploymentsResponses];

export type DeleteDeploymentData = {
    body?: never;
    path: {
        name: string;
    };
    query?: {
        /**
         * Namespace (internal; defaults to 'default').
         */
        namespace?: string;
    };
    url: '/v0/deployments/{name}';
};

export type DeleteDeploymentErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type DeleteDeploymentError = DeleteDeploymentErrors[keyof DeleteDeploymentErrors];

export type DeleteDeploymentResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteDeploymentResponse = DeleteDeploymentResponses[keyof DeleteDeploymentResponses];

export type GetLatestDeploymentData = {
    body?: never;
    path: {
        name: string;
    };
    query?: {
        /**
         * Namespace (internal; defaults to 'default').
         */
        namespace?: string;
    };
    url: '/v0/deployments/{name}';
};

export type GetLatestDeploymentErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetLatestDeploymentError = GetLatestDeploymentErrors[keyof GetLatestDeploymentErrors];

export type GetLatestDeploymentResponses = {
    /**
     * OK
     */
    200: Deployment;
};

export type GetLatestDeploymentResponse = GetLatestDeploymentResponses[keyof GetLatestDeploymentResponses];

export type ApplyDeploymentData = {
    body?: Deployment;
    path: {
        name: string;
    };
    query?: {
        /**
         * Namespace (internal; defaults to 'default').
         */
        namespace?: string;
    };
    url: '/v0/deployments/{name}';
};

export type ApplyDeploymentErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ApplyDeploymentError = ApplyDeploymentErrors[keyof ApplyDeploymentErrors];

export type ApplyDeploymentResponses = {
    /**
     * OK
     */
    200: Deployment;
};

export type ApplyDeploymentResponse = ApplyDeploymentResponses[keyof ApplyDeploymentResponses];

export type GetHealthV0Data = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v0/health';
};

export type GetHealthV0Errors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetHealthV0Error = GetHealthV0Errors[keyof GetHealthV0Errors];

export type GetHealthV0Responses = {
    /**
     * OK
     */
    200: HealthBody;
};

export type GetHealthV0Response = GetHealthV0Responses[keyof GetHealthV0Responses];

export type ListMcpserversData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Namespace (defaults to 'default'; 'all' lists across all namespaces).
         */
        namespace?: string;
        /**
         * Max items to return (default 50).
         */
        limit?: number;
        /**
         * Opaque pagination cursor.
         */
        cursor?: string;
        /**
         * Label selector: key=value,key2=value2.
         */
        labels?: string;
        /**
         * Restrict the result set to one tag value (tagged artifact kinds only).
         */
        tag?: string;
        /**
         * Only return the literal latest tag per (namespace, name). Equivalent to tag=latest for tagged kinds.
         */
        latestOnly?: boolean;
        /**
         * Include rows with a deletionTimestamp.
         */
        includeTerminating?: boolean;
    };
    url: '/v0/mcpservers';
};

export type ListMcpserversErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ListMcpserversError = ListMcpserversErrors[keyof ListMcpserversErrors];

export type ListMcpserversResponses = {
    /**
     * OK
     */
    200: ListOutputMcpServerBody;
};

export type ListMcpserversResponse = ListMcpserversResponses[keyof ListMcpserversResponses];

export type GetLatestMcpserverData = {
    body?: never;
    path: {
        name: string;
    };
    query?: {
        /**
         * Namespace (internal; defaults to 'default').
         */
        namespace?: string;
    };
    url: '/v0/mcpservers/{name}';
};

export type GetLatestMcpserverErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetLatestMcpserverError = GetLatestMcpserverErrors[keyof GetLatestMcpserverErrors];

export type GetLatestMcpserverResponses = {
    /**
     * OK
     */
    200: McpServer;
};

export type GetLatestMcpserverResponse = GetLatestMcpserverResponses[keyof GetLatestMcpserverResponses];

export type DeleteMcpserverData = {
    body?: never;
    path: {
        name: string;
        tag: string;
    };
    query?: {
        /**
         * Namespace (internal; defaults to 'default').
         */
        namespace?: string;
    };
    url: '/v0/mcpservers/{name}/{tag}';
};

export type DeleteMcpserverErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type DeleteMcpserverError = DeleteMcpserverErrors[keyof DeleteMcpserverErrors];

export type DeleteMcpserverResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteMcpserverResponse = DeleteMcpserverResponses[keyof DeleteMcpserverResponses];

export type GetMcpserverData = {
    body?: never;
    path: {
        name: string;
        tag: string;
    };
    query?: {
        /**
         * Namespace (internal; defaults to 'default').
         */
        namespace?: string;
    };
    url: '/v0/mcpservers/{name}/{tag}';
};

export type GetMcpserverErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetMcpserverError = GetMcpserverErrors[keyof GetMcpserverErrors];

export type GetMcpserverResponses = {
    /**
     * OK
     */
    200: McpServer;
};

export type GetMcpserverResponse = GetMcpserverResponses[keyof GetMcpserverResponses];

export type ListTagsMcpserverData = {
    body?: never;
    path: {
        name: string;
    };
    query?: {
        /**
         * Namespace (internal; defaults to 'default').
         */
        namespace?: string;
    };
    url: '/v0/mcpservers/{name}/tags';
};

export type ListTagsMcpserverErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ListTagsMcpserverError = ListTagsMcpserverErrors[keyof ListTagsMcpserverErrors];

export type ListTagsMcpserverResponses = {
    /**
     * OK
     */
    200: ListOutputMcpServerBody;
};

export type ListTagsMcpserverResponse = ListTagsMcpserverResponses[keyof ListTagsMcpserverResponses];

export type ListModelsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Namespace (defaults to 'default'; 'all' lists across all namespaces).
         */
        namespace?: string;
        /**
         * Max items to return (default 50).
         */
        limit?: number;
        /**
         * Opaque pagination cursor.
         */
        cursor?: string;
        /**
         * Label selector: key=value,key2=value2.
         */
        labels?: string;
        /**
         * Restrict the result set to one tag value (tagged artifact kinds only).
         */
        tag?: string;
        /**
         * Only return the literal latest tag per (namespace, name). Equivalent to tag=latest for tagged kinds.
         */
        latestOnly?: boolean;
        /**
         * Include rows with a deletionTimestamp.
         */
        includeTerminating?: boolean;
    };
    url: '/v0/models';
};

export type ListModelsErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ListModelsError = ListModelsErrors[keyof ListModelsErrors];

export type ListModelsResponses = {
    /**
     * OK
     */
    200: ListOutputModelBody;
};

export type ListModelsResponse = ListModelsResponses[keyof ListModelsResponses];

export type GetLatestModelData = {
    body?: never;
    path: {
        name: string;
    };
    query?: {
        /**
         * Namespace (internal; defaults to 'default').
         */
        namespace?: string;
    };
    url: '/v0/models/{name}';
};

export type GetLatestModelErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetLatestModelError = GetLatestModelErrors[keyof GetLatestModelErrors];

export type GetLatestModelResponses = {
    /**
     * OK
     */
    200: Model;
};

export type GetLatestModelResponse = GetLatestModelResponses[keyof GetLatestModelResponses];

export type DeleteModelData = {
    body?: never;
    path: {
        name: string;
        tag: string;
    };
    query?: {
        /**
         * Namespace (internal; defaults to 'default').
         */
        namespace?: string;
    };
    url: '/v0/models/{name}/{tag}';
};

export type DeleteModelErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type DeleteModelError = DeleteModelErrors[keyof DeleteModelErrors];

export type DeleteModelResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteModelResponse = DeleteModelResponses[keyof DeleteModelResponses];

export type GetModelData = {
    body?: never;
    path: {
        name: string;
        tag: string;
    };
    query?: {
        /**
         * Namespace (internal; defaults to 'default').
         */
        namespace?: string;
    };
    url: '/v0/models/{name}/{tag}';
};

export type GetModelErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetModelError = GetModelErrors[keyof GetModelErrors];

export type GetModelResponses = {
    /**
     * OK
     */
    200: Model;
};

export type GetModelResponse = GetModelResponses[keyof GetModelResponses];

export type ListTagsModelData = {
    body?: never;
    path: {
        name: string;
    };
    query?: {
        /**
         * Namespace (internal; defaults to 'default').
         */
        namespace?: string;
    };
    url: '/v0/models/{name}/tags';
};

export type ListTagsModelErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ListTagsModelError = ListTagsModelErrors[keyof ListTagsModelErrors];

export type ListTagsModelResponses = {
    /**
     * OK
     */
    200: ListOutputModelBody;
};

export type ListTagsModelResponse = ListTagsModelResponses[keyof ListTagsModelResponses];

export type PingV0Data = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v0/ping';
};

export type PingV0Errors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type PingV0Error = PingV0Errors[keyof PingV0Errors];

export type PingV0Responses = {
    /**
     * OK
     */
    200: PingBody;
};

export type PingV0Response = PingV0Responses[keyof PingV0Responses];

export type ListPluginsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Namespace (defaults to 'default'; 'all' lists across all namespaces).
         */
        namespace?: string;
        /**
         * Max items to return (default 50).
         */
        limit?: number;
        /**
         * Opaque pagination cursor.
         */
        cursor?: string;
        /**
         * Label selector: key=value,key2=value2.
         */
        labels?: string;
        /**
         * Restrict the result set to one tag value (tagged artifact kinds only).
         */
        tag?: string;
        /**
         * Only return the literal latest tag per (namespace, name). Equivalent to tag=latest for tagged kinds.
         */
        latestOnly?: boolean;
        /**
         * Include rows with a deletionTimestamp.
         */
        includeTerminating?: boolean;
    };
    url: '/v0/plugins';
};

export type ListPluginsErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ListPluginsError = ListPluginsErrors[keyof ListPluginsErrors];

export type ListPluginsResponses = {
    /**
     * OK
     */
    200: ListOutputPluginBody;
};

export type ListPluginsResponse = ListPluginsResponses[keyof ListPluginsResponses];

export type GetLatestPluginData = {
    body?: never;
    path: {
        name: string;
    };
    query?: {
        /**
         * Namespace (internal; defaults to 'default').
         */
        namespace?: string;
    };
    url: '/v0/plugins/{name}';
};

export type GetLatestPluginErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetLatestPluginError = GetLatestPluginErrors[keyof GetLatestPluginErrors];

export type GetLatestPluginResponses = {
    /**
     * OK
     */
    200: Plugin;
};

export type GetLatestPluginResponse = GetLatestPluginResponses[keyof GetLatestPluginResponses];

export type DeletePluginData = {
    body?: never;
    path: {
        name: string;
        tag: string;
    };
    query?: {
        /**
         * Namespace (internal; defaults to 'default').
         */
        namespace?: string;
    };
    url: '/v0/plugins/{name}/{tag}';
};

export type DeletePluginErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type DeletePluginError = DeletePluginErrors[keyof DeletePluginErrors];

export type DeletePluginResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeletePluginResponse = DeletePluginResponses[keyof DeletePluginResponses];

export type GetPluginData = {
    body?: never;
    path: {
        name: string;
        tag: string;
    };
    query?: {
        /**
         * Namespace (internal; defaults to 'default').
         */
        namespace?: string;
    };
    url: '/v0/plugins/{name}/{tag}';
};

export type GetPluginErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetPluginError = GetPluginErrors[keyof GetPluginErrors];

export type GetPluginResponses = {
    /**
     * OK
     */
    200: Plugin;
};

export type GetPluginResponse = GetPluginResponses[keyof GetPluginResponses];

export type ListTagsPluginData = {
    body?: never;
    path: {
        name: string;
    };
    query?: {
        /**
         * Namespace (internal; defaults to 'default').
         */
        namespace?: string;
    };
    url: '/v0/plugins/{name}/tags';
};

export type ListTagsPluginErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ListTagsPluginError = ListTagsPluginErrors[keyof ListTagsPluginErrors];

export type ListTagsPluginResponses = {
    /**
     * OK
     */
    200: ListOutputPluginBody;
};

export type ListTagsPluginResponse = ListTagsPluginResponses[keyof ListTagsPluginResponses];

export type ListPromptsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Namespace (defaults to 'default'; 'all' lists across all namespaces).
         */
        namespace?: string;
        /**
         * Max items to return (default 50).
         */
        limit?: number;
        /**
         * Opaque pagination cursor.
         */
        cursor?: string;
        /**
         * Label selector: key=value,key2=value2.
         */
        labels?: string;
        /**
         * Restrict the result set to one tag value (tagged artifact kinds only).
         */
        tag?: string;
        /**
         * Only return the literal latest tag per (namespace, name). Equivalent to tag=latest for tagged kinds.
         */
        latestOnly?: boolean;
        /**
         * Include rows with a deletionTimestamp.
         */
        includeTerminating?: boolean;
    };
    url: '/v0/prompts';
};

export type ListPromptsErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ListPromptsError = ListPromptsErrors[keyof ListPromptsErrors];

export type ListPromptsResponses = {
    /**
     * OK
     */
    200: ListOutputPromptBody;
};

export type ListPromptsResponse = ListPromptsResponses[keyof ListPromptsResponses];

export type GetLatestPromptData = {
    body?: never;
    path: {
        name: string;
    };
    query?: {
        /**
         * Namespace (internal; defaults to 'default').
         */
        namespace?: string;
    };
    url: '/v0/prompts/{name}';
};

export type GetLatestPromptErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetLatestPromptError = GetLatestPromptErrors[keyof GetLatestPromptErrors];

export type GetLatestPromptResponses = {
    /**
     * OK
     */
    200: Prompt;
};

export type GetLatestPromptResponse = GetLatestPromptResponses[keyof GetLatestPromptResponses];

export type DeletePromptData = {
    body?: never;
    path: {
        name: string;
        tag: string;
    };
    query?: {
        /**
         * Namespace (internal; defaults to 'default').
         */
        namespace?: string;
    };
    url: '/v0/prompts/{name}/{tag}';
};

export type DeletePromptErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type DeletePromptError = DeletePromptErrors[keyof DeletePromptErrors];

export type DeletePromptResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeletePromptResponse = DeletePromptResponses[keyof DeletePromptResponses];

export type GetPromptData = {
    body?: never;
    path: {
        name: string;
        tag: string;
    };
    query?: {
        /**
         * Namespace (internal; defaults to 'default').
         */
        namespace?: string;
    };
    url: '/v0/prompts/{name}/{tag}';
};

export type GetPromptErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetPromptError = GetPromptErrors[keyof GetPromptErrors];

export type GetPromptResponses = {
    /**
     * OK
     */
    200: Prompt;
};

export type GetPromptResponse = GetPromptResponses[keyof GetPromptResponses];

export type ListTagsPromptData = {
    body?: never;
    path: {
        name: string;
    };
    query?: {
        /**
         * Namespace (internal; defaults to 'default').
         */
        namespace?: string;
    };
    url: '/v0/prompts/{name}/tags';
};

export type ListTagsPromptErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ListTagsPromptError = ListTagsPromptErrors[keyof ListTagsPromptErrors];

export type ListTagsPromptResponses = {
    /**
     * OK
     */
    200: ListOutputPromptBody;
};

export type ListTagsPromptResponse = ListTagsPromptResponses[keyof ListTagsPromptResponses];

export type ListRuntimesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Namespace (defaults to 'default'; 'all' lists across all namespaces).
         */
        namespace?: string;
        /**
         * Max items to return (default 50).
         */
        limit?: number;
        /**
         * Opaque pagination cursor.
         */
        cursor?: string;
        /**
         * Label selector: key=value,key2=value2.
         */
        labels?: string;
        /**
         * Restrict the result set to one tag value (tagged artifact kinds only).
         */
        tag?: string;
        /**
         * Only return the literal latest tag per (namespace, name). Equivalent to tag=latest for tagged kinds.
         */
        latestOnly?: boolean;
        /**
         * Include rows with a deletionTimestamp.
         */
        includeTerminating?: boolean;
    };
    url: '/v0/runtimes';
};

export type ListRuntimesErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ListRuntimesError = ListRuntimesErrors[keyof ListRuntimesErrors];

export type ListRuntimesResponses = {
    /**
     * OK
     */
    200: ListOutputRuntimeBody;
};

export type ListRuntimesResponse = ListRuntimesResponses[keyof ListRuntimesResponses];

export type DeleteRuntimeData = {
    body?: never;
    path: {
        name: string;
    };
    query?: {
        /**
         * Namespace (internal; defaults to 'default').
         */
        namespace?: string;
    };
    url: '/v0/runtimes/{name}';
};

export type DeleteRuntimeErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type DeleteRuntimeError = DeleteRuntimeErrors[keyof DeleteRuntimeErrors];

export type DeleteRuntimeResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteRuntimeResponse = DeleteRuntimeResponses[keyof DeleteRuntimeResponses];

export type GetLatestRuntimeData = {
    body?: never;
    path: {
        name: string;
    };
    query?: {
        /**
         * Namespace (internal; defaults to 'default').
         */
        namespace?: string;
    };
    url: '/v0/runtimes/{name}';
};

export type GetLatestRuntimeErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetLatestRuntimeError = GetLatestRuntimeErrors[keyof GetLatestRuntimeErrors];

export type GetLatestRuntimeResponses = {
    /**
     * OK
     */
    200: Runtime;
};

export type GetLatestRuntimeResponse = GetLatestRuntimeResponses[keyof GetLatestRuntimeResponses];

export type ApplyRuntimeData = {
    body?: Runtime;
    path: {
        name: string;
    };
    query?: {
        /**
         * Namespace (internal; defaults to 'default').
         */
        namespace?: string;
    };
    url: '/v0/runtimes/{name}';
};

export type ApplyRuntimeErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ApplyRuntimeError = ApplyRuntimeErrors[keyof ApplyRuntimeErrors];

export type ApplyRuntimeResponses = {
    /**
     * OK
     */
    200: Runtime;
};

export type ApplyRuntimeResponse = ApplyRuntimeResponses[keyof ApplyRuntimeResponses];

export type ListSecretsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Namespace (defaults to 'default'; 'all' lists across all namespaces).
         */
        namespace?: string;
        /**
         * Max items to return (default 50).
         */
        limit?: number;
        /**
         * Opaque pagination cursor.
         */
        cursor?: string;
        /**
         * Label selector: key=value,key2=value2.
         */
        labels?: string;
        /**
         * Restrict the result set to one tag value (tagged artifact kinds only).
         */
        tag?: string;
        /**
         * Only return the literal latest tag per (namespace, name). Equivalent to tag=latest for tagged kinds.
         */
        latestOnly?: boolean;
        /**
         * Include rows with a deletionTimestamp.
         */
        includeTerminating?: boolean;
    };
    url: '/v0/secrets';
};

export type ListSecretsErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ListSecretsError = ListSecretsErrors[keyof ListSecretsErrors];

export type ListSecretsResponses = {
    /**
     * OK
     */
    200: ListOutputSecretBody;
};

export type ListSecretsResponse = ListSecretsResponses[keyof ListSecretsResponses];

export type DeleteSecretData = {
    body?: never;
    path: {
        name: string;
    };
    query?: {
        /**
         * Namespace (internal; defaults to 'default').
         */
        namespace?: string;
    };
    url: '/v0/secrets/{name}';
};

export type DeleteSecretErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type DeleteSecretError = DeleteSecretErrors[keyof DeleteSecretErrors];

export type DeleteSecretResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteSecretResponse = DeleteSecretResponses[keyof DeleteSecretResponses];

export type GetLatestSecretData = {
    body?: never;
    path: {
        name: string;
    };
    query?: {
        /**
         * Namespace (internal; defaults to 'default').
         */
        namespace?: string;
    };
    url: '/v0/secrets/{name}';
};

export type GetLatestSecretErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetLatestSecretError = GetLatestSecretErrors[keyof GetLatestSecretErrors];

export type GetLatestSecretResponses = {
    /**
     * OK
     */
    200: Secret;
};

export type GetLatestSecretResponse = GetLatestSecretResponses[keyof GetLatestSecretResponses];

export type ApplySecretData = {
    body?: Secret;
    path: {
        name: string;
    };
    query?: {
        /**
         * Namespace (internal; defaults to 'default').
         */
        namespace?: string;
    };
    url: '/v0/secrets/{name}';
};

export type ApplySecretErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ApplySecretError = ApplySecretErrors[keyof ApplySecretErrors];

export type ApplySecretResponses = {
    /**
     * OK
     */
    200: Secret;
};

export type ApplySecretResponse = ApplySecretResponses[keyof ApplySecretResponses];

export type ListSkillsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Namespace (defaults to 'default'; 'all' lists across all namespaces).
         */
        namespace?: string;
        /**
         * Max items to return (default 50).
         */
        limit?: number;
        /**
         * Opaque pagination cursor.
         */
        cursor?: string;
        /**
         * Label selector: key=value,key2=value2.
         */
        labels?: string;
        /**
         * Restrict the result set to one tag value (tagged artifact kinds only).
         */
        tag?: string;
        /**
         * Only return the literal latest tag per (namespace, name). Equivalent to tag=latest for tagged kinds.
         */
        latestOnly?: boolean;
        /**
         * Include rows with a deletionTimestamp.
         */
        includeTerminating?: boolean;
    };
    url: '/v0/skills';
};

export type ListSkillsErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ListSkillsError = ListSkillsErrors[keyof ListSkillsErrors];

export type ListSkillsResponses = {
    /**
     * OK
     */
    200: ListOutputSkillBody;
};

export type ListSkillsResponse = ListSkillsResponses[keyof ListSkillsResponses];

export type GetLatestSkillData = {
    body?: never;
    path: {
        name: string;
    };
    query?: {
        /**
         * Namespace (internal; defaults to 'default').
         */
        namespace?: string;
    };
    url: '/v0/skills/{name}';
};

export type GetLatestSkillErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetLatestSkillError = GetLatestSkillErrors[keyof GetLatestSkillErrors];

export type GetLatestSkillResponses = {
    /**
     * OK
     */
    200: Skill;
};

export type GetLatestSkillResponse = GetLatestSkillResponses[keyof GetLatestSkillResponses];

export type DeleteSkillData = {
    body?: never;
    path: {
        name: string;
        tag: string;
    };
    query?: {
        /**
         * Namespace (internal; defaults to 'default').
         */
        namespace?: string;
    };
    url: '/v0/skills/{name}/{tag}';
};

export type DeleteSkillErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type DeleteSkillError = DeleteSkillErrors[keyof DeleteSkillErrors];

export type DeleteSkillResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteSkillResponse = DeleteSkillResponses[keyof DeleteSkillResponses];

export type GetSkillData = {
    body?: never;
    path: {
        name: string;
        tag: string;
    };
    query?: {
        /**
         * Namespace (internal; defaults to 'default').
         */
        namespace?: string;
    };
    url: '/v0/skills/{name}/{tag}';
};

export type GetSkillErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetSkillError = GetSkillErrors[keyof GetSkillErrors];

export type GetSkillResponses = {
    /**
     * OK
     */
    200: Skill;
};

export type GetSkillResponse = GetSkillResponses[keyof GetSkillResponses];

export type ListTagsSkillData = {
    body?: never;
    path: {
        name: string;
    };
    query?: {
        /**
         * Namespace (internal; defaults to 'default').
         */
        namespace?: string;
    };
    url: '/v0/skills/{name}/tags';
};

export type ListTagsSkillErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ListTagsSkillError = ListTagsSkillErrors[keyof ListTagsSkillErrors];

export type ListTagsSkillResponses = {
    /**
     * OK
     */
    200: ListOutputSkillBody;
};

export type ListTagsSkillResponse = ListTagsSkillResponses[keyof ListTagsSkillResponses];

export type GetVersionV0Data = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v0/version';
};

export type GetVersionV0Errors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetVersionV0Error = GetVersionV0Errors[keyof GetVersionV0Errors];

export type GetVersionV0Responses = {
    /**
     * OK
     */
    200: VersionBody;
};

export type GetVersionV0Response = GetVersionV0Responses[keyof GetVersionV0Responses];
